### PR TITLE
Fix compositeindex issue 59

### LINKED ISSUE #59: "CompositeIndex" does not recognize reliably cases it cannot handle -- and performs wrong optimizations
`CompositeIndex` analyses a query and rewrites it if the index thinks it can optimize the query. Due to the rewriting it is necessary that it recognizes reliably the cases were the rewrite leads to a semantically equivalent query.

Currently, `CompositeIndex` operates on the query provided keys only and does not access its (true) component indexes. As a consequence, it cannot optimize a subquery when the relevant keys depend on the true component index, as this is the case for "range" queries.

`CompositeIndex` can currently wrongly optimize queries containing "range" subqueries - as demonstrated by the example below.
In #57, I have provided the new method `get_combiner_keys_info` which preprocesses a query (record) and determines the keys effectively used by the query. If `CompositeIndex` were ready to access the true composite index, then it could be used to remove the restriction.

`CompositeIndex` cannot optimize subqueries containing `not`.  It knows this and tries to recognize the case -- but its condition is wrong (actually, it checks for a "pure not", not a "general not"). As a consequence, it usually produces wrong optimizations for subqueries containing "not" (ignoring the "not") -- example below.
`CompositeIndex` could in principle optimize subqueries with "not". What it essentially does is
replace "Or(ai) and Or(bj)" with "Or(ai and bj)". It could also replace "(Or(ai) and NA) and (Or(bj) and NB)" (where the "NA" and "NB" represent optional "not" parts) with "Or(ai and bj) and NA and NB". If not missing, "NA" would be a "pure not". Such "not"s are costly. However, in the case above, a "filtering not" would be sufficient (provided it comes after the big "Or") as we know that any relevant document in indexed by "A" (similar for "B"). To support this efficiently, we would need to introduce "filtering queries" and ensure they are applied after the "normal" queries (note: `AdvancedQuery` supports filtering queries).

The following example demonstrates buggy optimizations by `CompositeIndex`:
```
>>> from Products.PluginIndexes.CompositeIndex.CompositeIndex import CompositeIndex
>>> from pprint import pprint as pp
>>> 
>>> ci = CompositeIndex(
...   "ci",
...   extra=[
...     dict(id="fi", meta_type="FieldIndex", attributes=("fi",)),
...     dict(id="ki", meta_type="KeywordIndex", attributes=("ki",)),
...     ]
...   )
>>> 
>>> ci._length.change(1)  # avoid premature return of `make_query`
>>> 
>>> pp(
... ci.make_query(dict(fi=dict(query=(1,2,3)),
...                    ki=dict(query=(10, 11)),
...                    ))
... )
{'ci': {'query': ((('fi', 1), ('ki', 10)),
                  (('fi', 1), ('ki', 11)),
                  (('fi', 2), ('ki', 10)),
                  (('fi', 2), ('ki', 11)),
                  (('fi', 3), ('ki', 10)),
                  (('fi', 3), ('ki', 11)))}}
>>> 
>>> # The query below could be equivalent to the former one (if e.g.
... #  "fi" has keys 1, 2 and 3) but the range is ignored and only
... #  the two values 1 and 3 are taken into account
... pp(
... ci.make_query(dict(fi=dict(query=(1, 3), range="min:max"),
...                    ki=dict(query=(10, 11)),
...                    ))
... )
{'ci': {'query': ((('fi', 1), ('ki', 10)),
                  (('fi', 1), ('ki', 11)),
                  (('fi', 3), ('ki', 10)),
                  (('fi', 3), ('ki', 11)))}}
>>> 
>>> # In the query below, the "not" is ignored
... pp(
... ci.make_query(dict(fi=dict(query=(1,2,3)),
...                    ki={"query":(10, 11), "not":15},
...                    ))
... )
{'ci': {'query': ((('fi', 1), ('ki', 10)),
                  (('fi', 1), ('ki', 11)),
                  (('fi', 2), ('ki', 10)),
                  (('fi', 2), ('ki', 11)),
                  (('fi', 3), ('ki', 10)),
                  (('fi', 3), ('ki', 11)))}}
```

### PR DESCRIPTION
**Pull request by andbag**
Fixes #59.

### CODE REVIEW

**Comment by d-maurer** [comment]
I have doubts that "pure not" is handled correctly.

```
>>> from Products.PluginIndexes.CompositeIndex.CompositeIndex import CompositeIndex
>>> from pprint import pprint as pp
>>> 
>>> ci = CompositeIndex(
...   "ci",
...   extra=[
...     dict(id="fi", meta_type="FieldIndex", attributes=("fi",)),
...     dict(id="ki", meta_type="KeywordIndex", attributes=("ki",)),
...     ]
...   )
>>> 
>>> ci._length.change(1)  # avoid premature return of `make_query`
>>> pp(
... ci.make_query(dict(fi=dict(query=(1,2,3)),
...                    ki={"not":(15,16)},
...                    ))
... )
{'ci': {'not': ((('fi', 3), ('ki', 15)),
                (('fi', 2), ('ki', 15)),
                (('fi', 1), ('ki', 15)),
                (('fi', 1), ('ki', 16)),
                (('fi', 3), ('ki', 16)),
                (('fi', 2), ('ki', 16))),
        'query': ((('fi', 1),), (('fi', 2),), (('fi', 3),))}}
>>> pp(
... ci.make_query(dict(fi={"not":1},
...                    ki={"not":(15,16)},
...                    ))
... )
{'ci': {'not': ((('fi', 1), ('ki', 15)), (('fi', 1), ('ki', 16))),
        'query': ((),)}}
>>> class O: fi = 0; ki = [0, 0]
... 
>>> ci.index_object(0, O)
True
>>> ci._apply_index(ci.make_query(dict(fi={"not":1},ki={"not":(15,16)},))) 
(IISet([]), ('ci',))
>>> list(ci._index.keys())
[(('fi', 0), ('ki', 0))]
```
The last result shows that the (example) composite index does not index 1 element tuples; thus the first "pure not" query will produce a (sometimes wrong) empty result.

The second "pure not" query also gives a wrong empty result.

**Comment by andbag** [comment]
@d-maurer Thanks for the clues. I had a thought error. Based on the values in the query, the query for the composite index cannot be rewritten for 'pure not' operations. The attribute with a 'pure not' operation will therefore not be considered.

```
>>> from Products.PluginIndexes.CompositeIndex.CompositeIndex import CompositeIndex
>>> from pprint import pprint as pp
>>> ci = CompositeIndex(
...     "ci",
...     extra=[
...         dict(id="fi", meta_type="FieldIndex", attributes=("fi",)),
...         dict(id="ki", meta_type="KeywordIndex", attributes=("ki",)),
...         dict(id='bi', meta_type='BooleanIndex', attributes=('bi',)),
...     ]
... )
>>> ci._length.change(1)  # avoid premature return of `make_query`
>>> 
>>> 
>>> query = dict(fi={'query': (1, 2, 3)},
...              ki={'not': (15, 16)},
...              bi={'query': (True,)})
>>> pp(ci.make_query(query))
{'ci': {'query': ((('fi', 1), ('bi', 1)),
                  (('fi', 2), ('bi', 1)),
                  (('fi', 3), ('bi', 1)))},
 'ki': {'not': (15, 16)}}

```

**Comment by d-maurer** [comment]
Andreas Gabriel wrote at 2019-4-3 13:54 +0000:
>@d-maurer Thanks for the clues. I had a thought error. Based on the values in the query, the query for the composite index cannot be rewritten for 'pure not' operations. The attribute with a 'pure not' operation will therefore not be considered.

Good!

The validity of your transform is based on:
    Or(a_i) and Not(Or(b_j)) = Or(ai) and Not(Or(a_i and b_j))

But a "pure not" implicitly changes the operator to "and" -
and we have already recognized that the transform
is not applicable for operator "and".

**Comment by andbag** [comment]
@icemac who merges the PR?

**Comment by icemac** [comment]
@andbag After successful review the writer of the PR merges it himself to prove he has signed the contributor agreement. I can cut a release afterwards if needed.

**Pull request merged**
