### PR TITLE
Implementation of getCounter logic for UnIndex etc.

### PR DESCRIPTION
**Pull request by andbag**
I implemented the getCounter logic (incl. tests) in order to support the request based caching of UnIndex based indexes. Currently I need some feedback from you. :)

### CODE REVIEW

**Comment by hannosch** [comment]
This looks really good to me. Would it be worthwhile to "document" the getCounter method and make it part of a new interface in PluginIndexes.interfaces? I wouldn't add it to the base IPluggableIndex, as there are other indices, like ZCTextIndex or elasticsearch/solr based index wrappers that might not want to implement this new method.

**Comment by andbag** [comment]
A new interface is a good idea. However, I believe that a new interface makes sense additionally including the caching logic methods, i.e. getCache etc. Or is there another intended purpose for the getCounter method?

**Comment by hannosch** [comment]
Right. A combined interface makes more sense. And I had trouble coming up with any name that describes getCounter on its own, something like IRequestCacheIndex is easier to spell out.

**Comment by andbag** [comment]
Should be the new Interface 'IRequestCacheIndex' a part of this PR?

Which methods should be implemented for the new interface?

Fine-grained?

class IRequestCacheIndex(ILimitedResultIndex)
   def getCounter():
   def getCacheKey():
   def getCache(key):
   def getRecordKey(record, resultset=None):
   def getCachedResult(key):
   etc.

Or simpler only one method?

class IRequestCacheIndex(ILimitedResultIndex)
    def getRequestCachedResult(record, resultset=None):

**Comment by hannosch** [comment]
I'd leave the interface out of this PR. Can't comment yet on the granularity question, as I haven't reviewed the other PR in detail.

I think this PR is fine as it is. Comments from anyone else?

**Comment by tseaver** [comment]
The implementation looks fine to me (well, I wish there was better factoring between `UnIndex` and its derived classes, but that isn't the fault of this PR).  Can we have a docstring for `UnIndex.getCounter` explaining its purpose?

**Comment by andbag** [comment]
Docstring added. :)

**Comment by hannosch** [comment]
Merged as a squashed commit via github's UI.

**Pull request merged**
