### PR TITLE
Add support for `not` queries in the `UUIDIndex`

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
See #98

**Comment by tisto** [comment]
@jensens @pbauer what's the process for this? Can we merge this PR now? Who is responsible for making releases for Zope?

**Comment by jugmac00** [comment]
Afaik there are no written rules, ie no real contributor documentation, which would be pretty good idea to create. Maybe at the next sprint, @icemac ?

Usually, there are these prerequisites:
- the committer needs a signed contributors agreement and creates a pr
- another committer needs to accept the pull request
- the creator of the pr merges the pr

That's the bare minimum.

Usually, for non trivial changes the reviewer should have a good knowledge of the package.

I think @d-maurer is the one with really deep knowledge about the ZCatalog, at least I would ask him for changes in the ZCatalog.

**Responsible for Releases**
There are no fixed releasers in the Zope community. You usually have to lookup the releaser of a package on PyPi and ask them.
https://pypi.org/project/Products.ZCatalog/

@hannosch is pretty much inactive, @tseaver answers occasional questions, but the other two are very active.

**Comment by tisto** [comment]
Thanks for the heads up @jugmac00! @sneridagh  has signed the contributor agreement and we have three PR reviews. I guess we are good to merge then.

@dataflake @icemac would it be possible to get a release that includes this merge?

**Comment by icemac** [comment]
I just released https://pypi.org/project/Products.ZCatalog/5.1/.

**Comment by sneridagh** [comment]
Thanks a lot @icemac !

**Comment by tisto** [comment]
Awesome! Thank you @icemac!

**Pull request merged**
