### PR TITLE
#54 Remove deprecated.

### PR DESCRIPTION
**Pull request by vernans**
ie Products.PluginIndexes.common and Products.ZCatalog.Lazy

### CODE REVIEW

**Review by dataflake — CHANGES_REQUESTED** [review]
In https://github.com/zopefoundation/Products.ZCatalog/issues/54#issuecomment-699837318 Steffen says he will add deprecation warnings. There needs to be some time between adding those and a release that removes the code. This is too fast.

**Comment by vernans** [comment]
@dataflake My comment on this issue wasn't ready yet. I added some information in the discussion. [#54 (comment)](https://github.com/zopefoundation/Products.ZCatalog/issues/54#issuecomment-699981551)

**Review by dataflake — COMMENTED** [review]
I cannot make a judgment here because I have no idea what code still uses these modules.

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
On second glance @vernans is right: The modules your PR removes had been marked with deprecation warnings for ZCatalog 5.0. The next release will be 5.2, so we're already past that deadline. I will merge this.

**Pull request merged**
